### ISSUE TITLE
Updated Visual Version

### ISSUE THREAD

**Issue by maneco2** [manusoft-gh/manusoft-daffodil#1]
Possible update the project also for working in 2019 or 2022 release VC?

**Comment by owenwengerd-octave** [comment]
The platform toolsets do actually work in VS 2017/2019/2022, but VS 2010 must be installed.

**Comment by maneco2** [comment]
We are trying to compile a project that requires V80, but unfortunately we are not successful, we are unable to do so, is there any tutorial on how to compile V80 with VS 2019? The team have discord or any contact method, if possible help? We send one email about.

**Comment by owenwengerd-octave** [comment]
For V80, you need VS 2005 (actually only the MSVC 8 platform tools) installed. In addition, you need VS 2010 installed. If those are installed and working, you should be able to open [test/Daffodil.sln](https://github.com/manusoft-gh/manusoft-daffodil/blob/main/test/DaffodilTest.sln) in VS 2019 and build without errors. Sorry, I am not able to help debug or support MSVC, however I am able to build the test projects successfully in VS 2019 on my system, so I know it is definitely possible.
