### ISSUE TITLE
v80 props has an extra space

### ISSUE THREAD

**Issue by icedream2linxi** [manusoft-gh/manusoft-daffodil#2]
There is an extra space in v80 props, causing the following error:
`TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.`

https://github.com/manusoft-gh/manusoft-daffodil/blob/main/source/Platforms/Win32/v80/Microsoft.Cpp.Win32.v80.props#L22

**Comment by owenwengerd** [comment]
Thanks for reporting. I've fixed it in R2.6.4.
